### ISSUE TITLE
Add updating the dispute fee based on changes to the stakeAmount

### ISSUE THREAD

**Issue by brendaloya** [tellor-io/tellorFlex#35]
This is for the 360 branch.

Hi, maybe there is a better way to go about it but as of now I've added a changeDisputeFee function that can only come from the oracle(flex) contract to update the dispute fee to being 10% of the stakeAmount. Since the stake amount changes in the _updateStakeAmount function I think it could go there or I can just calculate it on the fly when someone initiates a dispute. The problem I see with that is that unless they manually check the stake amount the dispute initiator does not know the dispute fee upfront.

These are the two lines I'm proposing(I don't think double asterisk is going to show correctly here so I used ^ :
             uint _disputeFee = stakeAmount / 10;
             IGovernance(governance).changeDisputeFee(_disputeFee);

In this function: 
 function _updateStakeAmount() internal {
         (bool valFound, bytes memory val, uint256 timestamp) = getDataBefore(
            trbUsdSpotPriceQueryId,
             block.timestamp - 12 hours
         );
         if (valFound) {
            uint256 priceTRB = abi.decode(val, (uint256));
             stakeAmount = (stakeAmountDollarTarget / priceTRB) * 10^18;
             **uint _disputeFee = stakeAmount / 10;
             IGovernance(governance).changeDisputeFee(_disputeFee);**
             emit NewStakeAmount(stakeAmount);
        }
     }

**Comment by tkernell** [comment]
That's a good point about not knowing the dispute fee up front. What if we add a getter to governance `getDisputeFee()`, which calls `oracle.getStakeAmount`, and then calculates the dispute fee on the fly? That way disputers could query the dispute fee, and flex's `_updateStakeAmount` function wouldn't have to call governance every time (especially for every `submitValue`). We could even lock in the current dispute fee at the beginning of the `beginDispute` function so that, even if the stakeAmount changes when `slashReporter` is called, the disputeFee remains the same for that particular dispute round.

**Comment by brendaloya** [comment]
I added the getDisputeFee() to the governance contract.
